// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tezvfxwcnulzitnigesg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRlenZmeHdjbnVseml0bmlnZXNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwODgxMjUsImV4cCI6MjA2NTY2NDEyNX0.OKFPwDVDWyTqMgy5BOSTzpISmOSjyjdMwy6j1Vyyxh4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);